# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor

tensor([[0.5878, 0.3750, 0.3806, 0.9686, 0.9000, 0.2063, 0.0977],
        [0.3668, 0.5157, 0.5313, 0.2648, 0.6227, 0.3770, 0.2261],
        [0.9176, 0.4971, 0.3127, 0.8527, 0.8244, 0.5946, 0.9475],
        [0.3074, 0.6310, 0.3224, 0.2775, 0.6572, 0.7256, 0.1003],
        [0.2021, 0.7594, 0.2100, 0.8590, 0.8472, 0.8836, 0.0317],
        [0.8418, 0.4639, 0.3704, 0.8589, 0.4251, 0.1235, 0.9336],
        [0.2944, 0.6769, 0.4224, 0.6154, 0.3716, 0.5538, 0.1729]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).


In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(size = (1,7))
# Perform matrix multiplication
print(random_tensor @ random_tensor_2.T)

tensor([[1.4151],
        [1.2355],
        [2.3952],
        [1.3469],
        [1.4599],
        [1.8171],
        [1.1518]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(size=(7,7))
t2 = torch.rand(size = (1,7))

# Matrix multiply tensors
torch.matmul(t1,t2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

`- Notes from documentation
   - `torch.cuda.manual_seed_all(seed)`
      - Set the seed for generating random numbers on all GPUs.

   - `torch.cuda.manual_seed(seed)`
      - Set the seed for generating random numbers for the current GPU.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# to make sure
import torch

if torch.cuda.is_available():
    device_count = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_count}")

    for i in range(device_count):
        gpu_name = torch.cuda.get_device_name(i)
        print(f"GPU {i}: {gpu_name}")
else:
    print("No GPU available")

Number of available GPUs: 1
GPU 0: Quadro T2000


In [18]:
# Set random seed

torch.manual_seed(1234)
# Check for access to GPU
# I did it in the previous cell

# Create two random tensors on GPU
Tensor_on_GPU_1= torch.rand(size=(2,3),
                            device = torch.device("cuda:0"))
Tensor_on_GPU_2= torch.rand(size=(2,3),
                            device = torch.device("cuda:0"))
Tensor_on_GPU_1 , Tensor_on_GPU_2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
matmul = Tensor_on_GPU_1 @ Tensor_on_GPU_2.T
matmul , matmul.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.


In [21]:
# Find max
max = matmul.max()

# Find min
min = matmul.min()

print(f'max: {max} , min: {min}')

max: 0.7667766809463501 , min: 0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(f"Index of max : {matmul.argmax(keepdim=True)}")
# Find arg min
print(f"Index of min : {matmul.argmin(keepdim=True)}")


Index of max : tensor([[1]], device='cuda:0')
Index of min : tensor([[0]], device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_x = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_y = tensor_x.squeeze()

# Print out tensors and their shapes

print(f"main tensor {tensor_x} , Shape {tensor_x.shape}")
print(f"squeeze tensor {tensor_y} , Shape {tensor_y.shape}")

main tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) , Shape torch.Size([1, 1, 1, 10])
squeeze tensor tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) , Shape torch.Size([10])


### check

In [12]:
torch.cuda.is_available()

True

In [13]:
torch.cuda.device_count()

1

Number of available GPUs: 1
GPU 0: Quadro T2000
